// Copyright (c) 2024-25 Darshan(@thisisthedarshan)
// Licensed under the MIT License. See LICENSE file for details.

import { RequestType } from "vscode-languageclient/node";

/* Custom request types for client and server */

/* This request and response pair are used with RequestDoxygenGeneration method  */
interface DoxygenGenerationRequest {
  line: string; /* Line contents since client isn't able to parse content but server can */
  /* To further ensure that we find the exact variable in case there are multiple of same type, 
     we get line number */
  lineNumber: number;
  /* For future implementation, we also get the fileURI */
  fileURI: string;
}

interface DoxygenGenerationResponse {
  content: string; /* The doxygen comment generated by the server */
  keyword: string; /* The keyword for which it was generated */
}

/* Custom Request Method Types */

/* The first type is for client to send a line and the server to 
   send a doxygen comment info for the first entity type it encounters.
   This excludes keywords but only has variable types, functions etc */
const RequestDoxygenGeneration = new RequestType<DoxygenGenerationRequest, DoxygenGenerationResponse, void>('dsp/RequestDoxygenGeneration');


export {
  DoxygenGenerationRequest,
  DoxygenGenerationResponse,
  RequestDoxygenGeneration,
};